name: Testy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Przywracanie pakietow
      run: dotnet restore tests/Fat32Formator.Tests.csproj

    - name: Kompilacja
      run: dotnet build tests/Fat32Formator.Tests.csproj --no-restore

    - name: Testy
      run: dotnet test tests/Fat32Formator.Tests.csproj --no-build --verbosity normal
